// ---------------------------------------------------------------------------
// Asset manifest — static require() map for Metro.
//
// Metro (RN's bundler) resolves assets at build time from LITERAL require()
// calls. Dynamic template strings like `require(\`.../\${key}.glb\`)` do NOT
// work — the resolver runs statically and can't see them. So every asset
// gets its own line here; the loader then maps AssetKey -> asset number.
// ---------------------------------------------------------------------------

export const ASSET_MODULES: Record<string, number> = {
  // -------------------- characters (KayKit skinned + animated) -------------
  knight: require("@/assets/game/knight-quest/characters/Knight.glb"),
  skeleton_minion: require("@/assets/game/knight-quest/characters/Skeleton_Minion.glb"),
  skeleton_rogue: require("@/assets/game/knight-quest/characters/Skeleton_Rogue.glb"),
  skeleton_mage: require("@/assets/game/knight-quest/characters/Skeleton_Mage.glb"),
  skeleton_warrior: require("@/assets/game/knight-quest/characters/Skeleton_Warrior.glb"),

  // Weapons — self-contained GLBs with the skeleton texture embedded in
  // each. No .bin or .png sidecars anymore.
  weapon_blade: require("@/assets/game/knight-quest/characters/Skeleton_Blade.glb"),
  weapon_axe: require("@/assets/game/knight-quest/characters/Skeleton_Axe.glb"),
  weapon_staff: require("@/assets/game/knight-quest/characters/Skeleton_Staff.glb"),

  // -------------------- dungeon (KayKit remastered) ------------------------
  floor_large: require("@/assets/game/knight-quest/dungeon/floor_tile_large.glb"),
  floor_small: require("@/assets/game/knight-quest/dungeon/floor_tile_small.glb"),
  floor_broken: require("@/assets/game/knight-quest/dungeon/floor_tile_small_broken_A.glb"),
  floor_weeds: require("@/assets/game/knight-quest/dungeon/floor_tile_small_weeds_A.glb"),
  floor_decorated: require("@/assets/game/knight-quest/dungeon/floor_tile_small_decorated.glb"),
  wall: require("@/assets/game/knight-quest/dungeon/wall.glb"),
  wall_corner: require("@/assets/game/knight-quest/dungeon/wall_corner.glb"),
  wall_doorway: require("@/assets/game/knight-quest/dungeon/wall_doorway.glb"),
  wall_gated: require("@/assets/game/knight-quest/dungeon/wall_gated.glb"),
  wall_pillar: require("@/assets/game/knight-quest/dungeon/wall_pillar.glb"),
  column: require("@/assets/game/knight-quest/dungeon/column.glb"),
  pillar: require("@/assets/game/knight-quest/dungeon/pillar.glb"),
  chest: require("@/assets/game/knight-quest/dungeon/chest.glb"),
  chest_gold: require("@/assets/game/knight-quest/dungeon/chest_gold.glb"),
  key: require("@/assets/game/knight-quest/dungeon/key.glb"),
  coin: require("@/assets/game/knight-quest/dungeon/coin.glb"),
  torch_mounted: require("@/assets/game/knight-quest/dungeon/torch_mounted.glb"),
  barrel_small: require("@/assets/game/knight-quest/dungeon/barrel_small.glb"),
  barrel_large: require("@/assets/game/knight-quest/dungeon/barrel_large.glb"),
  box_small: require("@/assets/game/knight-quest/dungeon/box_small.glb"),
  crates_stacked: require("@/assets/game/knight-quest/dungeon/crates_stacked.glb"),
  banner_red: require("@/assets/game/knight-quest/dungeon/banner_patternA_red.glb"),
  banner_blue: require("@/assets/game/knight-quest/dungeon/banner_patternA_blue.glb"),
  sword_shield: require("@/assets/game/knight-quest/dungeon/sword_shield.glb"),
  rubble_half: require("@/assets/game/knight-quest/dungeon/rubble_half.glb"),
  stairs: require("@/assets/game/knight-quest/dungeon/stairs.glb"),
  spikes: require("@/assets/game/knight-quest/dungeon/floor_tile_big_spikes.glb"),

  // -------------------- POLYGON village + overworld ------------------------
  poly_house_a: require("@/assets/game/knight-quest/polygon/house_a.glb"),
  poly_house_b: require("@/assets/game/knight-quest/polygon/house_b.glb"),
  poly_house_c: require("@/assets/game/knight-quest/polygon/house_c.glb"),
  poly_house_d: require("@/assets/game/knight-quest/polygon/house_d.glb"),
  poly_house_e: require("@/assets/game/knight-quest/polygon/house_e.glb"),
  poly_house_big: require("@/assets/game/knight-quest/polygon/house_big.glb"),
  poly_hut: require("@/assets/game/knight-quest/polygon/hut.glb"),
  poly_well: require("@/assets/game/knight-quest/polygon/well.glb"),
  poly_stall_a: require("@/assets/game/knight-quest/polygon/stall_a.glb"),
  poly_stall_b: require("@/assets/game/knight-quest/polygon/stall_b.glb"),
  poly_stall_cover_a: require("@/assets/game/knight-quest/polygon/stall_cover_a.glb"),
  poly_stall_cover_b: require("@/assets/game/knight-quest/polygon/stall_cover_b.glb"),
  poly_stall_table: require("@/assets/game/knight-quest/polygon/stall_table.glb"),
  poly_fence_a: require("@/assets/game/knight-quest/polygon/fence_a.glb"),
  poly_fence_b: require("@/assets/game/knight-quest/polygon/fence_b.glb"),
  poly_fence_post: require("@/assets/game/knight-quest/polygon/fence_post.glb"),
  poly_wall_stone: require("@/assets/game/knight-quest/polygon/wall_stone.glb"),
  poly_roadsign: require("@/assets/game/knight-quest/polygon/roadsign.glb"),
  poly_campfire: require("@/assets/game/knight-quest/polygon/campfire.glb"),
  poly_cart: require("@/assets/game/knight-quest/polygon/cart.glb"),
  poly_washingline: require("@/assets/game/knight-quest/polygon/washingline.glb"),
  poly_tree_a: require("@/assets/game/knight-quest/polygon/tree_a.glb"),
  poly_tree_b: require("@/assets/game/knight-quest/polygon/tree_b.glb"),
  poly_tree_c: require("@/assets/game/knight-quest/polygon/tree_c.glb"),
  poly_pine_a: require("@/assets/game/knight-quest/polygon/pine_a.glb"),
  poly_pine_b: require("@/assets/game/knight-quest/polygon/pine_b.glb"),
  poly_tree_birch: require("@/assets/game/knight-quest/polygon/tree_birch.glb"),
  poly_tree_dead: require("@/assets/game/knight-quest/polygon/tree_dead.glb"),
  poly_tree_stump: require("@/assets/game/knight-quest/polygon/tree_stump.glb"),
  poly_tree_log: require("@/assets/game/knight-quest/polygon/tree_log.glb"),
  poly_bush_a: require("@/assets/game/knight-quest/polygon/bush_a.glb"),
  poly_bush_b: require("@/assets/game/knight-quest/polygon/bush_b.glb"),
  poly_bush_c: require("@/assets/game/knight-quest/polygon/bush_c.glb"),
  poly_bush_d: require("@/assets/game/knight-quest/polygon/bush_d.glb"),
  poly_grass_a: require("@/assets/game/knight-quest/polygon/grass_a.glb"),
  poly_grass_b: require("@/assets/game/knight-quest/polygon/grass_b.glb"),
  poly_flower_a: require("@/assets/game/knight-quest/polygon/flower_a.glb"),
  poly_flower_b: require("@/assets/game/knight-quest/polygon/flower_b.glb"),
  poly_reeds: require("@/assets/game/knight-quest/polygon/reeds.glb"),
  poly_mushroom: require("@/assets/game/knight-quest/polygon/mushroom.glb"),
  poly_rock_a: require("@/assets/game/knight-quest/polygon/rock_a.glb"),
  poly_rock_b: require("@/assets/game/knight-quest/polygon/rock_b.glb"),
  poly_rock_flat: require("@/assets/game/knight-quest/polygon/rock_flat.glb"),
  poly_pebble_a: require("@/assets/game/knight-quest/polygon/pebble_a.glb"),
  poly_ground_grass_a: require("@/assets/game/knight-quest/polygon/ground_grass_a.glb"),
  poly_ground_grass_b: require("@/assets/game/knight-quest/polygon/ground_grass_b.glb"),
  poly_ground_dirt_a: require("@/assets/game/knight-quest/polygon/ground_dirt_a.glb"),
  poly_ground_dirt_b: require("@/assets/game/knight-quest/polygon/ground_dirt_b.glb"),
  poly_ground_stone: require("@/assets/game/knight-quest/polygon/ground_stone.glb"),
  poly_road_straight: require("@/assets/game/knight-quest/polygon/road_straight.glb"),
  poly_road_corner: require("@/assets/game/knight-quest/polygon/road_corner.glb"),
  poly_stream_straight: require("@/assets/game/knight-quest/polygon/stream_straight.glb"),
  poly_bridge: require("@/assets/game/knight-quest/polygon/bridge.glb"),
  poly_lillypad: require("@/assets/game/knight-quest/polygon/lillypad.glb"),
  poly_barrel_a: require("@/assets/game/knight-quest/polygon/poly_barrel_a.glb"),
  poly_crate_a: require("@/assets/game/knight-quest/polygon/poly_crate_a.glb"),
  poly_basket_a: require("@/assets/game/knight-quest/polygon/basket_a.glb"),
  poly_pot: require("@/assets/game/knight-quest/polygon/pot.glb"),
  poly_sack_a: require("@/assets/game/knight-quest/polygon/sack_a.glb"),
  poly_pumpkin: require("@/assets/game/knight-quest/polygon/pumpkin.glb"),
  poly_cheese: require("@/assets/game/knight-quest/polygon/cheese.glb"),
  poly_meat: require("@/assets/game/knight-quest/polygon/meat.glb"),
  poly_potion_a: require("@/assets/game/knight-quest/polygon/potion_a.glb"),
  poly_lantern: require("@/assets/game/knight-quest/polygon/lantern.glb"),
  poly_cloud_a: require("@/assets/game/knight-quest/polygon/cloud_a.glb"),
  poly_cloud_b: require("@/assets/game/knight-quest/polygon/cloud_b.glb"),
};

export type AssetKey = keyof typeof ASSET_MODULES;
