/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories-detail)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories-detail)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(storie)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(storie)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(subscribe)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(subscribe)'}/styles` | `/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(categories)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(categories)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(categories-detail)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(categories-detail)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(storie)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(storie)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(subscribe)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(subscribe)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(categories)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(categories)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(categories-detail)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(categories-detail)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(storie)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(storie)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorite${`?${string}` | `#${string}` | ''}` | `/favorite${`?${string}` | `#${string}` | ''}` | `${'/(subscribe)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(subscribe)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories-detail)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(categories-detail)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(storie)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(storie)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(subscribe)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(subscribe)'}/styles` | `/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
